### ISSUE TITLE
Clarification about broadphase checking

### ISSUE THREAD

**Issue by zplizzi** [BerkeleyAutomation/python-fcl#3]
In the readme, the broadphase checker is said to be able to "avoid n-squared complexity" (as is the purpose of the broad-phase, obviously). Then, one of the examples is `Managed internal (n^2) collision checking`. Does this mean that internal collision checking within a manager is n^2? If so, which operations are sub-n^2? I would be happy to update the readme with a bit clearer wording around this topic if someone can help me understand how exactly it works!

**Comment by mmatl** [comment]
Ah, by n^2 collision checking, I mean pairwise collision checking (i.e. n objects pairwise == n^2 possible pairs of objects checked for collision). Due to the way the manager works (efficient AABB trees), the collision checks are sub-quadratic in actual complexity. If you'd like to add a PR on this, let me know and I'll approve it.

**Comment by mmatl** [comment]
This has been fixed in 8c9cf688072ce259928c750383a00287f5d85575. Thanks for the comment!

**Comment by zplizzi** [comment]
Thanks!
